server:
  port: 8081

spring:
  application:
    name: sagelms-auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sagelms}
    username: ${DB_USER:sagelms}
    password: ${DB_PASSWORD:sagelms}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth

  flyway:
    schemas: auth
    baseline-on-migrate: true
