apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: sagelms
spec:
  interval: 10m
  releaseName: kyverno
  targetNamespace: kyverno
  chart:
    spec:
      chart: kyverno
      version: "3.8.1"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 1h
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    admissionController:
      replicas: 1
    backgroundController:
      replicas: 1
    cleanupController:
      replicas: 1
    reportsController:
      replicas: 1
