apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-tutor-secret
  labels:
    app.kubernetes.io/name: ai-tutor-service
    app.kubernetes.io/part-of: sagelms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-sagelms-devsecops
  target:
    name: ai-tutor-secret
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: sagelms-devsecops-google-api-key
