apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sagelms-devsecops
resources:
  - namespace.yaml
  - ../../base/apps
  - ai-tutor-externalsecret.yaml
  - app-shared-externalsecret.yaml
  - harbor-pull-externalsecret.yaml
  - ingress.yaml
  - managed-certificate.yaml
  - post-deploy-checker-rbac.yaml
images:
  - name: harbor.sagelms.id.vn/sagelms-app/gateway
    newName: harbor.sagelms.id.vn/sagelms-app/gateway
    newTag: 9229a5baad32c94d5f355c98329b7d149af4e587
    digest: sha256:4a31743c51daabdb9c2fccb829ac3ed999be53616bfb3e8226d51fbe8990de89
  - name: harbor.sagelms.id.vn/sagelms-app/auth-service
    newName: harbor.sagelms.id.vn/sagelms-app/auth-service
    newTag: 9229a5baad32c94d5f355c98329b7d149af4e587
    digest: sha256:2de63881fe5f72a28ba019858960881e5015a35d19d0034b514277ebce0ac516
  - name: harbor.sagelms.id.vn/sagelms-app/course-service
    newName: harbor.sagelms.id.vn/sagelms-app/course-service
    newTag: 9229a5baad32c94d5f355c98329b7d149af4e587
    digest: sha256:7293b5f6ddb82fab8653fd94b2cf269b495279c1ac0b160ada1b745e9a0af805
  - name: harbor.sagelms.id.vn/sagelms-app/content-service
    newName: harbor.sagelms.id.vn/sagelms-app/content-service
    newTag: 9229a5baad32c94d5f355c98329b7d149af4e587
    digest: sha256:514c25f57f91885f1c1346dd4a4280becd7471c02c4a954f59ee70b2fa30001b
  - name: harbor.sagelms.id.vn/sagelms-app/progress-service
    newName: harbor.sagelms.id.vn/sagelms-app/progress-service
    newTag: 9229a5baad32c94d5f355c98329b7d149af4e587
    digest: sha256:dfb15ce96fdf13219feb9c2d2992e1824be510c82c0cd6571007d766cb3385d8
  - name: harbor.sagelms.id.vn/sagelms-app/assessment-service
    newName: harbor.sagelms.id.vn/sagelms-app/assessment-service
    newTag: 9229a5baad32c94d5f355c98329b7d149af4e587
    digest: sha256:4391acea9119080965b4145f76ea4fb22248bf85751a353eaa61da9f6cb80eb1
  - name: harbor.sagelms.id.vn/sagelms-app/challenge-service
    newName: harbor.sagelms.id.vn/sagelms-app/challenge-service
    newTag: 9229a5baad32c94d5f355c98329b7d149af4e587
    digest: sha256:1f683777a6c061e6e1f74795cb449530be5411e9d6034892a35d6bd10f419c04
  - name: harbor.sagelms.id.vn/sagelms-app/ai-tutor-service
    newName: harbor.sagelms.id.vn/sagelms-app/ai-tutor-service
    newTag: dev
  - name: harbor.sagelms.id.vn/sagelms-app/web
    newName: harbor.sagelms.id.vn/sagelms-app/web
    newTag: 9229a5baad32c94d5f355c98329b7d149af4e587
    digest: sha256:4835beaa07a60003fc8ffc0fd311f93e9eebd8053cbef22e44e3387d50c14706
patches:
  - target:
      kind: ServiceAccount
      labelSelector: app.kubernetes.io/part-of=sagelms
    patch: |-
      - op: add
        path: /imagePullSecrets
        value:
          - name: harbor-pull-secret
  - target:
      kind: Service
      name: gateway
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cloud.google.com/neg: '{"ingress": true}'
  - target:
      kind: ConfigMap
      name: assessment-service-config
    patch: |-
      - op: add
        path: /data/SPRING_FLYWAY_ENABLED
        value: "false"
      - op: add
        path: /data/SPRING_JPA_HIBERNATE_DDL_AUTO
        value: "update"
  - target:
      kind: Service
      name: web
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cloud.google.com/neg: '{"ingress": true}'
