apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: post-deploy-checker
  namespace: sagelms-devsecops
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: post-deploy-checker-gha
  namespace: sagelms-devsecops
subjects:
  - kind: User
    name: sagelms-devsecops-gha-sa@sagelms.iam.gserviceaccount.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: post-deploy-checker
  apiGroup: rbac.authorization.k8s.io
