apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sagelms-dev

resources: []
# Sẽ bổ sung khi có deployment manifests:
# - ../namespaces/dev.yaml
# - deployment-auth.yaml
# - deployment-course.yaml
# - ...
