apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sagelms-devsecops-monitoring-targets
  namespace: fluxcd
spec:
  interval: 5m
  path: ./infra/k8s/devsecops/monitoring/targets
  prune: true
  sourceRef:
    kind: GitRepository
    name: sagelms
  dependsOn:
    - name: sagelms-devsecops-monitoring
  timeout: 5m
  wait: true
